GET http://localhost:3000


POST http://localhost:3000
Content-Type: application/json

{
    "name": "Testando",
    "channel": "Testado"
}


PATCH http://localhost:3000
Content-Type: application/json

{
    "name": "Testefull"
}

DELETE http://localhost:3000
